// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PVP.Models;

namespace PVP.Migrations
{
    [DbContext(typeof(PVPContext))]
    [Migration("20220327103138_DBFullHotfix")]
    partial class DBFullHotfix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("PVP.Models.Device", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("fk_user")
                        .HasColumnType("int")
                        .HasColumnName("fk_user");

                    b.Property<bool>("is_on")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_on");

                    b.Property<bool>("is_realtime")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_realtime");

                    b.Property<string>("setup_string")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("setup_string");

                    b.Property<string>("tag")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tag");

                    b.Property<int>("treshold")
                        .HasColumnType("int")
                        .HasColumnName("treshold");

                    b.HasKey("id")
                        .HasName("id");

                    b.HasIndex("fk_user")
                        .HasDatabaseName("fk_user");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("PVP.Models.Info", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("date_time")
                        .HasColumnType("datetime")
                        .HasColumnName("date_time");

                    b.Property<int>("fk_device_id")
                        .HasColumnType("int")
                        .HasColumnName("fk_device_id");

                    b.Property<int>("wattage")
                        .HasColumnType("int")
                        .HasColumnName("wattage");

                    b.HasKey("id")
                        .HasName("id");

                    b.HasIndex("fk_device_id")
                        .HasDatabaseName("fk_device_id");

                    b.ToTable("Infos");
                });

            modelBuilder.Entity("PVP.Models.RealtimeInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("fk_device_id")
                        .HasColumnType("int")
                        .HasColumnName("fk_device_id");

                    b.Property<int>("wattage")
                        .HasColumnType("int")
                        .HasColumnName("wattage");

                    b.HasKey("id")
                        .HasName("id");

                    b.HasIndex("fk_device_id")
                        .HasDatabaseName("fk_device_id");

                    b.ToTable("RealtimeInfos");
                });

            modelBuilder.Entity("PVP.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("pass_hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("id")
                        .HasName("id");

                    b.HasIndex("mail")
                        .HasDatabaseName("Email");

                    b.HasIndex("pass_hash")
                        .HasDatabaseName("Pass_hash");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PVP.Models.Device", b =>
                {
                    b.HasOne("PVP.Models.User", "fk_userNavigation")
                        .WithMany("Devices")
                        .HasForeignKey("fk_user")
                        .HasConstraintName("has")
                        .IsRequired();

                    b.Navigation("fk_userNavigation");
                });

            modelBuilder.Entity("PVP.Models.Info", b =>
                {
                    b.HasOne("PVP.Models.Device", "fk_device_idNavigation")
                        .WithMany("Infos")
                        .HasForeignKey("fk_device_id")
                        .HasConstraintName("shows")
                        .IsRequired();

                    b.Navigation("fk_device_idNavigation");
                });

            modelBuilder.Entity("PVP.Models.Device", b =>
                {
                    b.Navigation("Infos");
                });

            modelBuilder.Entity("PVP.Models.User", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
